INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Adriana Aparecida Simao', 'feminino', '29/10/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Adriana Lucia De Souza', 'feminino', '28/04/1970');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Adriana Melo De Andrade', 'feminino', '03/02/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Aide De Souza Pacheco', 'feminino', '30/11/2022');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Alair Teresinha Luiz', 'feminino', '15/03/1960');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Alexandre Donaire Pereira Jorge', 'masculino', '27/06/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Aline Fonseca Martins', 'feminino', '18/01/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Alyne Cristine Martins E Martins', 'feminino', '02/11/1990');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Amanda Cristina De Santana', 'feminino', '26/01/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Amarilis De Almeida Pereira', 'feminino', '19/01/1937');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Carolina Ramos Costas', 'feminino', '04/04/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Carolina Spinelli Castex', 'feminino', '28/08/1990');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Clara', 'feminino', '17/06/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Claudia Goncalves De Siqueira', 'feminino', '14/01/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Eli De Oliveira', 'feminino', '12/06/1938');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Lu Viera Dias', 'feminino', '01/02/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Luiza Congedo Carrieni', 'feminino', '27/07/1987');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Luiza De Oliveira Ribeiro', 'feminino', '14/11/1972');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Maria Gentil Alves', 'feminino', '31/01/1986');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ana Paula Dantas Barata', 'feminino', '08/07/1993');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Andrea Castello Dos Santos', 'feminino', '06/04/1971');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Andres Abellan Hellin', 'masculino', '07/03/1968');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Andrew Rocha Silva', 'masculino', '16/03/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Angela Maria Franzese De Santana', 'feminino', '29/01/1965');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Angela Maria Verre', 'feminino', '24/03/1965');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Angelina Goncalves Couto Hellin', 'feminino', '17/04/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Angelo Antonio Pires De Oliveira', 'masculino', '14/11/1991');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Antonio Carregalo Martin', 'masculino', '28/09/1953');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Audra Liz Magalhaes', 'feminino', '08/10/1980');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Auria Cavalcante De Souza', 'feminino', '18/11/1967');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Beatriz Da Silva Matildes', 'feminino', '10/10/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Bernadino Serra', 'masculino', '08/11/1943');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Carmen Oliveiro Ribeiro Matos', 'feminino', '20/04/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Caroline Cao', 'feminino', '29/02/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Caue De Sa Dias Morgardo', 'masculino', '21/04/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Cecilia De Souza Carvalho', 'feminino', '28/02/1978');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Celia Cristina Dos Santos Bispo Bartolotto', 'feminino', '12/08/1976');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Celia Dos Santos Cruz Santana', 'feminino', '21/08/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Celia Rodrigues Ribeiro', 'feminino', '02/01/1960');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Cibele Rodrigues Da Silva', 'feminino', '17/06/1988');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Cintia Maria Dos Santos', 'feminino', '28/05/1987');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Claudia Ventura Da Cruz Souza', 'feminino', '24/08/1962');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Clayton Moreira Da Silva', 'masculino', '15/11/1989');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Clecio Augusto Da Silva', 'masculino', '18/12/1970');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Cristriane Franco', 'feminino', '21/09/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Cyra Fernandes', 'feminino', '20/05/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Dalva Aparecida Martins', 'feminino', '19/05/1963');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Daniel Barreto Monteiro', 'masculino', '10/05/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Daniela Goldberg', 'feminino', '05/10/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Daphne Silva Santana', 'feminino', '10/01/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Debora Flori De Azevedo', 'feminino', '13/02/1977');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Debora Franco', 'feminino', '27/09/1994');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Diego Andrade Alves De Freitas', 'masculino', '17/05/1984');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Diva Ramona', 'feminino', '23/02/1970');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Donizete Oliveira Dos Santos', 'masculino', '23/03/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Edilene Izidio Alves', 'feminino', '07/10/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Edson Francisco Da Silva Alvim', 'masculino', '09/09/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Eduardo Duda Nascimento', 'masculino', '17/12/2008');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Eliane Santos Nunes', 'feminino', '15/07/1977');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Elisabete Dos Santos', 'feminino', '31/12/1956');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Emily De Jesus Bezerra', 'feminino', '05/03/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Evelun Ariane Mendes Costa', 'masculino', '11/03/1991');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Evelyn E Felisberto', 'feminino', '29/01/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Evilyn Vieira Santos', 'feminino', '07/06/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fabiana Roberta Fontes Cruz', 'feminino', '07/11/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fabricio Da Conceicao Gravata', 'masculino', '17/12/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fatima Pereira De Brito', 'feminino', '27/11/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Felipe Romera Pereira', 'masculino', '20/03/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fellipe De Almeida Bueno Capoupo', 'masculino', '17/10/1984');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fernanda De Lima Moreira', 'feminino', '24/12/1981');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fernanda Martins Das Neves Lopes', 'feminino', '26/12/2005');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Fernando Silva Rodrigues', 'masculino', '31/10/1989');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Flavia De Jesus Santos', 'feminino', '24/04/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Flavia Nasser Villela', 'feminino', '18/10/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Flavia Santos Silva', 'feminino', '30/12/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Flavio Russo Pinto', 'feminino', '28/08/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Franciele  De Oliveira', 'feminino', '17/08/1980');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gabriel Pereira', 'masculino', '10/06/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gabriela Do Nascimento Silva', 'feminino', '14/11/1989');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gabriela Geisa F Pimenta', 'feminino', '18/02/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gabriela Ribeiro', 'feminino', '16/10/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gabriela Vicente', 'feminino', '10/12/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gena Paula Rodrigues Avelino', 'feminino', '14/03/1980');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gildet Pereira Da Silva', 'feminino', '14/03/1976');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gisley Da Silva Louzada', 'feminino', '04/09/1980');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Gustavo Bispo Bartolotto', 'masculino', '02/08/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Harley Cristiane De Lucas Lima Dos Santos', 'feminino', '21/05/1975');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Helena Estevao Coelhp', 'feminino', '10/01/1955');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Hellen Vite De Andrade', 'feminino', '04/05/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Heloisa Gattai Gomes  De Franca', 'feminino', '14/04/1975');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Henrique Roberto Dos Santos', 'masculino', '16/12/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Hesther  Pinheiro Albuquerque', 'feminino', '28/04/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Hilda De Jesus Gomes', 'feminino', '16/08/1961');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Igor Ferreira Marcondes', 'masculino', '15/09/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isabel Cristina Geraldo', 'feminino', '06/08/1957');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isabel Cristina Vasconcelos R Vieira Santos', 'feminino', '23/12/1983');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isabel Da Cruz Silva', 'feminino', '09/06/1963');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isabel Gomes Rodrigues', 'feminino', '05/06/1961');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isabelle Castello Torres', 'feminino', '03/04/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Isadora De Moraes Servo', 'feminino', '10/05/2014');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ivone Felix Dos Santos', 'feminino', '25/08/1957');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jefferson Rosa Rodrigues', 'masculino', '03/02/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jessica Silva', 'feminino', '23/10/1986');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jessica Silva Sao Jose', 'feminino', '23/10/1986');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Joao Victor Nascimento Silva', 'masculino', '12/10/2005');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Joelma Santana Santos', 'feminino', '20/06/1997');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jose Renato Mendes', 'masculino', '21/09/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jose Victor Dias', 'masculino', '15/10/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Josefa Iderio Do Nascimento', 'feminino', '24/01/1948');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jucineide Borges Rodrigues', 'feminino', '04/11/1965');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Juliana Barboza Da Silva', 'feminino', '21/08/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Juliana Cristina Barbosa', 'feminino', '23/07/1995');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Juliana Ferreira Da Silva', 'feminino', '28/06/1986');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Juliana Thauis Lopes', 'feminino', '19/08/2024');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jussara Dos Santos Lino', 'feminino', '10/04/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Jussara Ferraz Da Cunha', 'feminino', '13/03/1957');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Kassandra Ramos Bueno Araujo', 'feminino', '12/02/1981');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Katia Gizele De Abreu Saab', 'feminino', '23/02/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Lais Aika Bilesky Onaga', 'feminino', '15/03/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Lais Santos Dos Reis Diefenteller', 'feminino', '10/06/1988');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Larissa Nobrega Bezerra', 'feminino', '25/01/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Larissa Sena Pereira', 'feminino', '08/03/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Laura Ferreira Piasentin', 'feminino', '15/01/2014');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Leandra Alves Rosete', 'feminino', '01/08/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Leo Batista Silva', 'masculino', '22/06/1994');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Leticia Da Silva De Moura', 'feminino', '01/04/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Leticia Fonseta Teixeira', 'feminino', '07/05/2007');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Leticia Raya Moreira', 'feminino', '16/10/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luana Santos Valle', 'feminino', '15/01/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luane De Oliveira Santas Macedo', 'feminino', '16/12/1990');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Lucas Francisco Justo', 'masculino', '09/07/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luciana Santos Reis', 'feminino', '03/07/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luciano Dos Santos Machado', 'masculino', '22/06/1969');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Lucymeira Baptistella Monteiro', 'feminino', '13/12/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Ludmila Lopes Duarte', 'feminino', '09/09/2005');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luis Felipe Wenceslay Angotti', 'masculino', '23/06/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luiz Carlos Lago', 'masculino', '18/01/1969');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luiz Carlos Moreira', 'masculino', '24/12/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luiz Torres', 'masculino', '23/07/1937');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luma Camargo De Oliveira', 'feminino', '12/09/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Luma Martins Da Silva', 'feminino', '11/04/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Magali Lomao', 'feminino', '04/10/1972');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Manoel Moreira Trindade', 'masculino', '27/03/1953');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Manuela Toumillon Adegas', 'feminino', '29/12/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marcela Alves Dos Sc Da Silva', 'feminino', '03/09/1988');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marcella Castrucci Correia', 'feminino', '08/11/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marcelly Pereira De Andrade', 'feminino', '19/10/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marcia Mauricio De Almeida', 'feminino', '15/03/1993');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marcio Andre Barboza Felisberto', 'masculino', '13/02/1985');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marco Antonio', 'masculino', '23/02/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Aparecida Aniz Silva De Oliveira', 'feminino', '10/02/1971');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Aparecida Dutra Ventura', 'feminino', '22/10/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Beatriz Santos Andrade', 'feminino', '09/10/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Clotildes Gentil', 'feminino', '03/06/1961');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Cristina Dos Santos', 'feminino', '15/07/1965');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Cristina Pinto', 'feminino', '17/02/1960');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Da Conceicao Pereira Navarro', 'feminino', '03/11/1966');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Da Graca Giordano', 'feminino', '13/06/1960');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Dalva Figueuiredo', 'feminino', '28/10/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Edilene Sousa', 'feminino', '21/02/1969');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Eduarda Almeida Galvao', 'feminino', '08/11/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Eduarda Migliorini Ferreira', 'feminino', '13/02/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Elisa Cardoso De Mendonca', 'feminino', '08/04/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Eliza Cardoso De Mendonca', 'feminino', '08/04/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Emilia Gomes Rodrigues', 'feminino', '29/06/1956');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Fatima De Jesus Martins', 'feminino', '11/12/1958');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Helena Gomes Bezerra', 'feminino', '19/06/1958');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Rosa Lourenco Antunes', 'feminino', '20/02/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Maria Roseli Da Silva', 'feminino', '16/12/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mariana Laura Galvao', 'feminino', '23/07/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mariana Reis Santana', 'feminino', '26/06/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mariane Miranda Da Silva', 'feminino', '21/04/1987');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mariani Lourenco', 'feminino', '13/09/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mariene Pereira Ramos', 'feminino', '03/06/1978');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marinalva Do Nascimento Silva', 'feminino', '20/06/1961');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marino Moreira Alvares Junior', 'masculino', '05/01/1981');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marjorie Marques Felicio Da Silva', 'feminino', '28/10/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Marlene Teresinha Garcia', 'feminino', '28/03/1952');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mary Romy Saito', 'feminino', '09/05/1963');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Matheus Danos Teixeira', 'masculino', '08/04/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Matheus Eduardo Ribeiro', 'masculino', '13/03/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Matheus Kolarik Miranda', 'masculino', '27/11/1995');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Matheus Silva Moreira', 'masculino', '28/03/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mercedes Suzano Riesco', 'feminino', '13/01/1954');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Michele Santana De Almeida', 'feminino', '12/01/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Michelle Oliveira Venalha', 'feminino', '23/06/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Michelle Uemura', 'feminino', '13/03/1975');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Milton Do Nascimento', 'masculino', '08/01/1958');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Milva Machado De Souza', 'feminino', '07/12/1970');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Mirelle Vieira', 'feminino', '11/11/1987');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Miriam Aparecida Moreira Rodrigues', 'feminino', '08/05/1945');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Morgana Gomes De Araujo Dos Santos', 'feminino', '16/05/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nagela Carla Alves', 'feminino', '30/09/1992');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Naroane Leticia Martins Pires', 'feminino', '29/05/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Natali Da Silva Santos', 'feminino', '28/05/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Natalia Dos Santos Felipe', 'feminino', '15/01/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nataly Da Silva Gravanich', 'feminino', '08/02/1993');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Natalya Vicente', 'feminino', '12/03/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nathalia Pacheco Basile Homsy', 'feminino', '24/09/1997');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nayara Goncalves Da Silva', 'feminino', '08/04/1992');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nayara Santos Monteiro Da Silva', 'feminino', '05/02/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nicholas Mannuel Mariano Furtado', 'masculino', '01/05/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Nicole Victoria Valerio Da Silva', 'feminino', '18/02/2004');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Patricia Aparecida Soares Russo Pinto', 'feminino', '23/08/1971');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Paulo Rogerio Rodrigues Dos Santos', 'masculino', '29/02/1988');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Priscila Dos Santos Cruvenel Do Nascimento', 'feminino', '09/01/1987');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rafaela Cescato Cipriano', 'feminino', '21/07/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Regina Celia A Dos S C Da Silva', 'feminino', '18/02/1956');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rejane Da Anunciacao Sabino', 'feminino', '08/04/1984');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Renan Nunes Cabral', 'masculino', '02/06/1993');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Renata Da Silva Fonseca', 'feminino', '12/01/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Renata De Lima Bernardo', 'feminino', '08/10/1978');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Renato Cauto Vinhosa', 'masculino', '31/10/1957');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rita De Cassia De Castro', 'feminino', '20/02/1967');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Roberta Melo Ferreira Veloso', 'feminino', '11/04/1981');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rodney Davi Araujo Pereira', 'masculino', '08/06/1974');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rosana Alves De Lima', 'feminino', '05/03/1972');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Rosana Aparecida De Almeida Alves', 'feminino', '23/06/1964');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sabrina Dos Santos Alves', 'feminino', '12/05/1998');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Samantha Rocha Dos Santos', 'feminino', '25/07/2000');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sandra Carolina Fragoso Monteiro', 'feminino', '11/07/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sandra Mariela Steinberg Gonzaga Oliveira', 'feminino', '06/10/1968');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sandra Massako', 'feminino', '24/01/1958');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sangela Cruz', 'feminino', '08/06/2003');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Severina Tereza Da Silva', 'feminino', '29/03/1948');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Silvana Dos Santos Rodrigues', 'feminino', '30/08/1957');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Simone Dos Santos Rosa', 'feminino', '05/03/1973');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Solange De Oliveira Bonovich', 'feminino', '01/09/1968');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Solange Nogueira Da Silva Nascimento', 'feminino', '14/09/1962');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sonia Regina Ribeiro', 'feminino', '02/10/1950');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sthefani De Andrade Silva', 'feminino', '08/12/1997');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Sueli Cristina Ferreira Cabral', 'feminino', '30/03/1968');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Suzana De Jesus', 'feminino', '04/04/1996');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Tamires Dos Santos Araujo Antunes', 'feminino', '03/06/1991');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Tania Regina Passos De Mattos', 'feminino', '15/08/1960');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Tatiana Fernanda Goncalves', 'feminino', '10/09/1979');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Tayanra Guimaraes Inacio', 'feminino', '12/02/1988');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Thaina Aparecida Viriato De Lima', 'feminino', '11/12/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Thalita Conceicao Nagahama', 'feminino', '09/02/1982');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Thatiane Cardoso Zeferino', 'feminino', '24/04/1978');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Valeria Pinho Gomes', 'feminino', '18/07/1983');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Vanessa Fragoso Monteiro', 'feminino', '12/12/1975');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Veridiana Dutra Ventura Barcellos', 'feminino', '15/10/1999');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Victoria Padilha De Souza Santos', 'feminino', '07/08/2002');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Victoria Santos Silva', 'feminino', '30/12/2001');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Vitor Figueiredo Rosa Rodrigues', 'masculino', '31/10/2006');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Vivian Santos', 'feminino', '26/09/1995');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Wagner Werneck De Novaes', 'masculino', '15/07/1989');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Willian Giovannini', 'masculino', '30/12/1997');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Wilma Nancy Pontuchka', 'feminino', '05/07/1940');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Wilson Ferreira Lima', 'masculino', '12/08/1972');
INSERT INTO paciente ("nome", "sexo", "data_nascimento") VALUES ('Yasmin Gomes', 'feminino', '17/06/1994');