
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Arklok\Documents\Projetos\FACULDADE\anamnese\repository\src\GUI\Home\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x500")
window.configure(bg = "#FAFDFF")


canvas = Canvas(
    window,
    bg = "#FAFDFF",
    height = 500,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=142.0,
    y=357.0,
    width=316.0,
    height=100.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    276.0,
    244.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    276.0,
    244.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#9EAEB8",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=61.0,
    y=224.0,
    width=430.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=521.0,
    y=219.0,
    width=50.0,
    height=50.0
)

canvas.create_text(
    46.0,
    188.0,
    anchor="nw",
    text="Caminho do Arquivo",
    fill="#032157",
    font=("Inter", 16 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    145.0,
    71.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
