
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Arklok\Documents\Projetos\FACULDADE\anamnese\repository\src\GUI\Processing\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("960x540")
window.configure(bg = "#FAFDFF")


canvas = Canvas(
    window,
    bg = "#FAFDFF",
    height = 540,
    width = 960,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=713.0,
    y=477.0,
    width=100.0,
    height=41.88607406616211
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=835.5,
    y=477.0,
    width=100.0,
    height=41.772151947021484
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=458.0,
    y=320.0,
    width=42.5,
    height=42.5
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=458.5,
    y=177.5,
    width=42.5,
    height=42.5
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    723.0,
    254.5,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    723.0,
    270.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    236.0,
    254.5,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    236.0,
    270.0,
    image=image_image_4
)

canvas.create_text(
    23.0,
    27.5,
    anchor="nw",
    text="[Processamento]",
    fill="#032157",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    23.0,
    491.0,
    anchor="nw",
    text="Ao clicar em processar, você concorda em inserir os dados da tabela à esquerda no banco de dados",
    fill="#032157",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    23.0,
    504.0,
    anchor="nw",
    text="de produção do sistema do ambulatório. ",
    fill="#032157",
    font=("Inter", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
